Repository param-code/counter-app, pull requests merged in 2024-10, with the labels that each got.

#11 feat : Added Timer Page
  package-lock.json
  package.json
  src/App.jsx
  src/components/SwitchTab.jsx
  src/pages/AutoCounterPage.jsx
  src/pages/TimerPage.css
  src/pages/TimerPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#13 Add responsive world clock feature with country selection
  eslint.config.js
  package-lock.json
  package.json
  src/App.jsx
  src/components/navbar.jsx
  src/pages/AutoCounterPage.jsx
  src/pages/WorldClockPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#14 Enhance Stopwatch with Lap Time Analysis and Visualization Features
  src/components/LapAnalysis.jsx
  src/components/LapVisualization.jsx
  src/components/laplist.jsx
  src/components/timer.jsx
  src/pages/AutoCounterPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#20 Updted README.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#26 logo-update-by-nk
  src/assets/logo.png
  src/components/navbar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#24 Updated Readme File
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level2

#28 Toggle theme icon functionality improved
  package-lock.json
  package.json
  src/App.jsx
  src/components/Footer.jsx
  src/components/navbar.jsx
  src/pages/WorldClockPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#57 Added Contributors profile
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#51 changed the twitter logo to X logo
  package-lock.json
  src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#18 Need Enhancement of Button UI Problem Solved
  src/components/controls.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest2024

#34 Corrected the navigation thing
  src/components/navbar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#41 Add two more button to navigate timer & world clock with cool animation
  src/assets/clock.png
  src/assets/timer1.png
  src/components/css/navbar.css
  src/components/navbar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#42 feat : Added Darkmode Logo which for dark theme
  src/assets/dark.jpg
  src/components/navbar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#63 Bug-Fix: Fixing Position of Footer across pages
  src/App.jsx
  src/pages/AutoCounterPage.jsx
  src/pages/TimerPage.jsx
  src/pages/WorldClockPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#84 Code of conduct file added
  Code of Conduct.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#74 Create footer.css
  footer.css
  footer.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#73 Feature(Docker) : add production-ready Dockerfile #67
  Dockerfile
Labels: gssoc-ext, hacktoberfest-accepted, level1

#85 Added issue templates for custom issues, bugs, and feature requests. Fixes #48
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/custom_issue_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#78 changes made in scrolling part of laps
  package-lock.json
  package.json
  src/assets/image_with_black_background.png
  src/components/laplist.jsx
  src/pages/TimerPage.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#72 Timer Feature Added
  src/components/audio/alert-85101.mp3
  src/components/pop-up.jsx
  src/pages/AutoCounterPage.jsx
  src/pages/TimerPage.css
  src/pages/TimerPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#104 added signIn toggle functionality
  src/pages/SignUpPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#105 fixed for darkmode
  src/pages/TimerPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#107 google multilanguage integrated
  package-lock.json
  package.json
  src/components/Footer.jsx
  src/components/GoogleTranslate.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#108 added progress bar
  package-lock.json
  package.json
  src/components/controls.jsx
  src/components/timer.jsx
  src/pages/Counter.jsx
  tailwind.config.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#109 Added a new Logo & AutoChange of theme for the selected TimeZone.
  README.md
  src/assets/darklogo1.png
  src/assets/logo1.png
  src/components/navbar.jsx
  src/pages/WorldClockPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#111 BUG: Adding placeholder in SignupPage
  src/pages/SignUpPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#113 BUG: Remove Double border
  src/pages/SignUpPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#115 Feat: Toast feature added for notification
  package.json
  src/main.jsx
  src/pages/SignUpPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#120 Added features and improvements to footer section
  src/assets/clock_img.png
  src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#121 Fix Footer Hyperlink Issue and Improve Layout by Removing Redundancy
  package-lock.json
  src/App.jsx
  src/components/Footer.jsx
  src/components/navbar.jsx
  src/main.jsx
  src/pages/TimerPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#123 Updated README for navigable table of contents
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#126 Fixed password toggle and updated packages
  package-lock.json
  package.json
  src/pages/SignUpPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#128 ✨added local storage✨
  src/pages/SignUpPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#130 Fixed "Website Opens at the Bottom of the Page Upon Load"
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#129 README.md file updated with "IMPORTANT GUIDELINES","COMMUTNITY GUIDELINES" and "CODE REVIEWS"
  readme1.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#135 Fix start and stop button margins
  src/components/controls.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#136 Added Contributor's Page
  package-lock.json
  package.json
  src/App.jsx
  src/components/Footer.jsx
  src/pages/Contributors.css
  src/pages/Contributors.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#137 Fixed dark theme issue #122
  src/components/navbar.jsx
  src/pages/WorldClockPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#148 Feat: Added login and signup functionality
  backend/.env
  backend/.gitignore
  backend/config/database.js
  backend/controllers/auth.js
  backend/index.js
  backend/models/User.js
  backend/package-lock.json
  backend/package.json
  package.json
  src/App.jsx
  src/assets/login.png
  src/assets/signup.png
  src/components/Auth/LoginForm.jsx
  src/components/Auth/SignupForm.jsx
  src/components/Auth/Template.jsx
  src/components/navbar.jsx
  src/main.jsx
  src/reducer/index.js
  src/services/apiConnector.js
  src/services/apis.js
  src/services/operations/authAPI.js
  src/slices/authSlice.js
  src/slices/profileSlice.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#154 rectified negative timer ,and added popups.
  package-lock.json
  src/pages/TimerPage.css
  src/pages/TimerPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#138 improve preloader and scroll bar
  index.html
  preloader.js
  preloaderStyle.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#139 Enhance ui of signup
  src/pages/SignUpPage.css
  src/pages/SignUpPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#158 Added Navbar and Dark theme in contributor page (Issue no #144)
  package-lock.json
  src/pages/Contributors.css
  src/pages/Contributors.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#160 added dockerignore file
  .dockerignore
Labels: gssoc-ext, hacktoberfest-accepted, level1

#161 fixed issue : #159
  src/components/Footer.jsx
  src/components/laplist.jsx
  src/index.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#163 Add about_page
  package-lock.json
  src/App.jsx
  src/components/About.jsx
  src/components/navbar.jsx
  src/components/ui/card.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#164 Added sections to nav bar
  footer.css
  footer.html
  index.html
  src/App.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#168 Added Spotify player
  src/App.jsx
  src/components/SpotifyPlayer.css
  src/components/SpotifyPlayer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#182 Dark mode in stopwatch page and sign up minor issue
  src/pages/Counter.jsx
  src/pages/SignUpPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#186 work tracker added : #79 done
  src/App.jsx
  src/pages/AutoCounterPage.jsx
  src/pages/WorkTracker.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#187 Added Lap Time Proportional Analysis Pie Chart, Bar Graph and a Progress Graph
  package.json
  src/components/CumulativeTimeChart.jsx
  src/components/LapAnalysis.jsx
  src/components/LapBarChart.jsx
  src/components/LapPieChart.jsx
  src/pages/AutoCounterPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#193 Auth page responsiveness issue fixed.
  src/components/Auth/Template.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#198 added validation
  backend/package-lock.json
  backend/package.json
  package-lock.json
  package.json
  src/components/Auth/LoginForm.jsx
  src/components/Auth/SignupForm.jsx
  src/validations/validation.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#203 Added dark theme in "WorkTracker page"
  src/pages/WorkTracker.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#204 [Bug]: Spotify Music Player Window hovers Appears Unexpectedly.
  package-lock.json
  package.json
  src/components/SpotifyPlayer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#207 [Bug] : #176 Dark mode is not functional in about us page
  src/components/About.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#209 added dockerfile
  backend/Dockerfile
Labels: gssoc-ext, hacktoberfest-accepted, level1

#214 converted image to webp
  src/assets/afternoonBackground.webp
  src/assets/clock.webp
  src/assets/clock_img.webp
  src/assets/dark.webp
  src/assets/darklogo1.webp
  src/assets/image_with_black_background.webp
  src/assets/login.webp
  src/assets/logo.webp
  src/assets/logo1.webp
  src/assets/morningBackground.webp
  src/assets/nightBackground.webp
  src/assets/signup.webp
  src/assets/timer1.webp
  src/components/Auth/Template.jsx
  src/components/Footer.jsx
  src/components/navbar.jsx
  src/pages/WorldClockPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#218 Fix: Google Translate Dropdown Not Clickable in Footer
  src/components/GoogleTranslate.jsx
  src/slices/authSlice.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#224 Added Scroll to top button
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#227 [Bug]: #226 Home Page Starts from the Bottom on Direct Load
  src/pages/AutoCounterPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted

#235 Updated Navbar component for improved responsiveness and functionality
  src/components/navbar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#230 Contributors page added to Navbar
  src/components/navbar.jsx
  src/pages/WorkTracker.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#236 Added Error404 page
  src/App.jsx
  src/pages/Error404.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#238 New Privacy and Policy is added
  src/App.jsx
  src/components/Footer.jsx
  src/pages/PrivacyPolicy.css
  src/pages/PrivacyPolicy.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#253 Added 3d hover on logo improve the styling of footer heading and footer items
  src/components/Footer.jsx
  src/components/css/Footer.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#247 Password-Recovery-Feature
  package-lock.json
  src/App.jsx
  src/components/Auth/LoginForm.jsx
  src/components/Auth/PasswordRecovery.jsx
  src/services/operations/authAPI.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#254 Update README.md added Stargazers and Forkers section
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#256 Adding google sign in
  backend/.env
  backend/controllers/auth.js
  backend/models/User.js
  package-lock.json
  package.json
Labels: gssoc-ext, hacktoberfest-accepted, level2

#259 Successfully updated code_of_conduct.md file
  Code of Conduct.md
  Code_of_conduct.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#261 Enhanced the UI of login and signup pages
  package-lock.json
  src/components/Auth/LoginForm.jsx
  src/components/Auth/LoginImage.jsx
  src/components/Auth/SignupForm.jsx
  src/components/Auth/SignupImage.jsx
  src/components/Auth/Template.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#264 Added Table to Display Repository Statistics in README.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#265 RATE US feature solves issue #241
  src/components/Auth/Review.jsx
  src/main.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#275 Added feedback Form
  src/App.jsx
  src/components/Auth/LoginForm.jsx
  src/components/Footer.jsx
  src/pages/Feedback.css
  src/pages/Feedback.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#277 Feature : About Page Improved
  src/components/About.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#281 Done enhancements and also added some new sections
  Contributing.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#282 Feedback backend frontend functionality working #278 done
  backend/.env
  backend/controllers/othercontrollers.js
  backend/index.js
  backend/package-lock.json
  backend/package.json
  src/pages/Feedback.css
  src/pages/Feedback.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#280 enhanced scroll to top feature
  index.html
  src/components/Auth/SignupForm.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#283 refactor(Auth Actions): Centralize Logic and Improve Code Maintainability
  src/services/operations/authAPI.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#294 added paging to contributors
  src/pages/Contributors.css
  src/pages/Contributors.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#301 solved worktracker overlap issue
  src/pages/WorkTracker.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#302 [Bug]: rate us page is having issues #293
  src/components/Auth/Review.jsx
  src/components/SpotifyPlayer.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#310 Change the eye toggle button in Login Page
  src/components/Auth/LoginForm.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#317 enhanced privacy page
  src/components/Auth/LoginForm.jsx
  src/components/Auth/SignupForm.jsx
  src/pages/PrivacyPolicy.css
  src/pages/PrivacyPolicy.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1
